version: '3'
name: auth

services:
  # PostgreSQL server
  database:
    image: postgres:16.3-alpine3.20
    container_name: database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data/:rw
    networks:
        - app-network
    healthcheck:
      test: ["CMD", "pg_isready" ,"-h", "localhost"]
      interval: 1m
      timeout: 5s
      retries: 10

volumes:
  db-data:

networks:
  app-network:
    driver: bridge

