version: '3'
name: auth

services:
  app:
    build:
      context: ../
      dockerfile: build/app.Dockerfile
    image: auth_server:latest
    container_name: app
    environment:
      - DATABASE_LINK=host=database user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} port=5432 sslmode=disable
      - SIGN_KEY=${SIGN_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    networks:
      - app-network
    ports:
      - ${APP_PORT}:8000
    depends_on:
      database:
        condition: service_healthy

